# Generated by Django 3.2 on 2022-12-03 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0005_auto_20221124_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('1', 'active'), ('2', 'deleted')], max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_name', models.CharField(blank=True, max_length=300, null=True)),
                ('pickup_location', models.CharField(blank=True, max_length=300, null=True)),
                ('dropoff_location', models.CharField(blank=True, max_length=300, null=True)),
                ('pickup_location_coordinates', jsonfield.fields.JSONField(default=dict)),
                ('dropoff_location_coordinates', jsonfield.fields.JSONField(default=dict)),
                ('job_status', models.CharField(blank=True, choices=[('1', 'Pending'), ('2', 'In Progress'), ('3', 'Completed')], default='1', max_length=200, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.customer')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
