# Generated by Django 3.2 on 2022-11-24 10:38

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0005_auto_20221124_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('1', 'active'), ('2', 'deleted')], max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_name', models.CharField(blank=True, max_length=300, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=300, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=300, null=True)),
                ('vehicle_company', models.CharField(blank=True, max_length=300, null=True)),
                ('vehicle_last_location', jsonfield.fields.JSONField(default=dict)),
                ('vehicle_fuel', models.CharField(blank=True, max_length=300, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
