# Generated by Django 3.2 on 2022-11-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle-avatar/'),
        ),
    ]
